### ISSUE TITLE
Support for node v12.x

### ISSUE THREAD

**Issue by dhessler** [blueconic/node-oom-heapdump#8]
Hello,

I am running node v12.x, which includes improved async stack traces.
I'm trying to debug a potential memory leak in one of my applications, where taking snapshots is consistently crashing the process, and found this library which looks really promising.

Unfortunately the build is failing on node 12.7.0; I get a little further after naively updating all dependencies to their latest versions:

```
npm install

> gc-stats@1.4.0 install ******/node-oom-heapdump/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@12.7.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
  SOLINK_MODULE(target) Release/gcstats.node
  COPY ******/node-oom-heapdump/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v72-darwin-x64/gcstats.node
  TOUCH Release/obj.target/action_after_build.stamp

> node-oom-heapdump@1.1.4 install ******/node-oom-heapdump
> node-gyp rebuild

  CXX(target) Release/obj.target/node_oom_heapdump_native/lib/node_oom_heapdump_native.o
../lib/node_oom_heapdump_native.cc:77:44: error: no matching member function for call to
      'ToString'
  String::Utf8Value fArg(isolate, args[0]->ToString());
                                  ~~~~~~~~~^~~~~~~~
/Users/david/.node-gyp/12.7.0/include/node/v8.h:2535:44: note: candidate function not
      viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/david/.node-gyp/12.7.0/include/node/v8.h:2551:31: note: candidate function not
      viable: requires single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
../lib/node_oom_heapdump_native.cc:83:27: error: no matching member function for call to
      'BooleanValue'
  addTimestamp = args[1]->BooleanValue();
                 ~~~~~~~~~^~~~~~~~~~~~
/Users/david/.node-gyp/12.7.0/include/node/v8.h:2566:8: note: candidate function not
      viable: requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/david/.node-gyp/12.7.0/include/node/v8.h:2569:51: note: candidate function not
      viable: requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
2 errors generated.
make: *** [Release/obj.target/node_oom_heapdump_native/lib/node_oom_heapdump_native.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ******/node-oom-heapdump
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-oom-heapdump@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-oom-heapdump@1.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Do you expect to add support for node 12 anytime soon?
Thanks!

**Comment by paulrutter** [comment]
Hi @dhessler,

Yes, the company i work for is planning to move to Node 12 when it becomes LTS in october.
Part of that upgrade is making sure this module works on 12 as well.

So yes, i expect to add support for Node 12 in the near future.

Regards,

**Comment by paulrutter** [comment]
I haven't been able to test it thoroughly, but i managed to modify the native code to compile for Node.js 12. I've committed my code in a branch (node12) and published a "beta" version on npm, to test with.

See https://www.npmjs.com/package/node-oom-heapdump/v/1.2.0-beta.0.
Let me know what your experiences are.

**Comment by dhessler** [comment]
wow thanks @paulrutter for the quick investigation! definitely happy to beta test when ready.

**Comment by paulrutter** [comment]
I'm having a hard time getting it to work on Node.js 12.x.
See https://github.com/nodejs/node/issues/27552#issuecomment-538742818.

I think i'll need help from the v8 team in order to proceed.
It seems that the API's haven't changed, but the context in which the API is called no longer seems to work on Node.js 12.

To be continued.

**Comment by paulrutter** [comment]
I'm closing the issue for now.
Let me know when you encounter any issues by filing a new issue.

**Comment by jorisw** [comment]
@paulrutter Which were the flags causing Node 12 to run badly? I'm having the same problem with v2.0.0 on Node 12.10.

**Comment by paulrutter** [comment]
See https://github.com/blueconic/node-oom-heapdump/pull/9/commits/fac8e9226a351c495c5923bfedf42bffc056fb13
These were:

* --optimize_for_size 
* --always_compact
